//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FreeSpace", ReplyAction="http://tempuri.org/IService1/FreeSpaceResponse")]
        string FreeSpace(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FreeSpace", ReplyAction="http://tempuri.org/IService1/FreeSpaceResponse")]
        System.Threading.Tasks.Task<string> FreeSpaceAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TotalSpace", ReplyAction="http://tempuri.org/IService1/TotalSpaceResponse")]
        string TotalSpace(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TotalSpace", ReplyAction="http://tempuri.org/IService1/TotalSpaceResponse")]
        System.Threading.Tasks.Task<string> TotalSpaceAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FreeSpace(string name) {
            return base.Channel.FreeSpace(name);
        }
        
        public System.Threading.Tasks.Task<string> FreeSpaceAsync(string name) {
            return base.Channel.FreeSpaceAsync(name);
        }
        
        public string TotalSpace(string name) {
            return base.Channel.TotalSpace(name);
        }
        
        public System.Threading.Tasks.Task<string> TotalSpaceAsync(string name) {
            return base.Channel.TotalSpaceAsync(name);
        }
    }
}
